-- ============================================================================
-- Example 16: 3D Soft Body Pressurized Ball & Volumetric Jelly Cubes
-- Demonstrates:
-- - Internal pressure simulation (n*R*T model) on a soft sphere
-- - Dynamic runtime pressure inflation/deflation (UP / DOWN keys)
-- - Tetrahedron volume constraints on elastic jelly cubes
-- - Two-way collision response against static steps and dynamic rigid bodies
-- - Batched fast wireframe debug renderer with constraint visualization
-- ============================================================================

local cam = {
    x = 0.0, y = 7.0, z = 16.0,
    yaw = -90.0, pitch = -18.0,
    fov = 60.0
}

local soft_ball = nil
local jelly_cubes = {}
local rigid_obstacles = {}
local pressure_val = 20000.0
local show_debug = true
local floor_body = nil

local function reset_scene()
    crayon.physics3d.destroyAll()
    jelly_cubes = {}
    rigid_obstacles = {}

    -- Ground plane
    floor_body = crayon.physics3d.createPlane(0, 0, 0, 0, 1, 0, 50.0)

    -- Staircase / incline obstacles out of static rigid bodies
    for i = 1, 6 do
        local step_y = (i - 1) * 0.8
        local step_z = -8.0 + (i - 1) * 2.0
        crayon.physics3d.createBox(0, step_y + 0.4, step_z, 6.0, 0.4, 1.0, "static", 0.4, 0.1)
    end

    -- Dynamic rigid boxes on the ground to be pushed around by the soft bodies
    for i = -2, 2 do
        local rb = crayon.physics3d.createBox(i * 1.5, 0.5, 7.0, 0.5, 0.5, 0.5, "dynamic", 0.5, 0.3)
        table.insert(rigid_obstacles, rb)
    end

    -- 1. Pressurized Soft Ball (positional factory — matches C++ signature)
    --    create_soft_body_sphere(origin, radius, rings, sectors, compliance, pressure)
    soft_ball = crayon.physics3d.createSoftBodySphere(
        -1.5, 10.0, -7.0,
        1.2,          -- radius
        12,           -- rings
        16,           -- sectors
        0.00005,      -- compliance
        pressure_val  -- pressure
    )

    -- 2. Volumetric Jelly Cubes (positional factory)
    --    create_soft_body_cube(origin, size, grid_size, compliance, pressure)
    --    Note: volume constraints are auto-generated by the cube factory; we
    --    just pick a compliance that makes the result feel like jelly.
    local jelly1 = crayon.physics3d.createSoftBodyCube(
        1.5, 9.0, -7.0,
        1.4,      -- size
        3,        -- grid subdivisions
        0.0005,   -- compliance (edge/volume)
        0.0       -- pressure
    )
    table.insert(jelly_cubes, jelly1)

    local jelly2 = crayon.physics3d.createSoftBodyCube(
        0.0, 13.0, -6.0,
        1.2,      -- size
        3,        -- grid subdivisions
        0.001,    -- compliance
        0.0       -- pressure
    )
    table.insert(jelly_cubes, jelly2)
end

function crayon.init()
    crayon.window.setWindowSize(480, 360)
    crayon.window.setResolution(480, 360)
    crayon.window.setTitle("Crayon Engine - 3D Soft Body Ball & Volumetric Jelly")
    crayon.graphics.setLight(-0.4, -1.0, -0.6, 1.0, 0.95, 0.85, 0.25, 0.25, 0.3)
    reset_scene()
end

function crayon.update(dt)
    -- Camera controls
    local move_speed = 9.0 * dt
    local rot_speed = 60.0 * dt

    local rad_yaw = math.rad(cam.yaw)
    local rad_pitch = math.rad(cam.pitch)
    local fwd_x = math.cos(rad_pitch) * math.sin(rad_yaw)
    local fwd_y = math.sin(rad_pitch)
    local fwd_z = -math.cos(rad_pitch) * math.cos(rad_yaw)
    local rgt_x = math.cos(rad_yaw)
    local rgt_z = math.sin(rad_yaw)

    if crayon.input.isDown("w") then
        cam.x = cam.x + fwd_x * move_speed
        cam.y = cam.y + fwd_y * move_speed
        cam.z = cam.z + fwd_z * move_speed
    end
    if crayon.input.isDown("s") then
        cam.x = cam.x - fwd_x * move_speed
        cam.y = cam.y - fwd_y * move_speed
        cam.z = cam.z - fwd_z * move_speed
    end
    if crayon.input.isDown("a") then
        cam.x = cam.x - rgt_x * move_speed
        cam.z = cam.z - rgt_z * move_speed
    end
    if crayon.input.isDown("d") then
        cam.x = cam.x + rgt_x * move_speed
        cam.z = cam.z + rgt_z * move_speed
    end
    if crayon.input.isDown("space") then cam.y = cam.y + move_speed end
    if crayon.input.isDown("lshift") then cam.y = cam.y - move_speed end

    if crayon.input.isDown("left")  then cam.yaw = cam.yaw - rot_speed end
    if crayon.input.isDown("right") then cam.yaw = cam.yaw + rot_speed end
    if crayon.input.isDown("up")    then cam.pitch = math.min(85.0, cam.pitch + rot_speed) end
    if crayon.input.isDown("down")  then cam.pitch = math.max(-85.0, cam.pitch - rot_speed) end

    -- Runtime Pressure Inflation / Deflation
    if crayon.input.isDown("e") then
        pressure_val = pressure_val + 20000.0 * dt
        if soft_ball and soft_ball:isValid() then
            soft_ball:setPressure(pressure_val)
        end
    end
    if crayon.input.isDown("q") then
        pressure_val = math.max(0.0, pressure_val - 20000.0 * dt)
        if soft_ball and soft_ball:isValid() then
            soft_ball:setPressure(pressure_val)
        end
    end

    -- Toggle debug
    if crayon.input.isPressed("tab") then
        show_debug = not show_debug
    end

    -- Reset scene
    if crayon.input.isPressed("r") then
        reset_scene()
    end

    -- Kick ball upward — applyImpulse on all vertices
    -- Signature: softBody:applyImpulse(x, y, z)  (global form, no vertex index)
    if crayon.input.isPressed("k") and soft_ball and soft_ball:isValid() then
        soft_ball:applyImpulse(0.0, 15.0, 0.0)
    end
    
    crayon.physics3d.step(dt)
end

function crayon.draw()
    crayon.graphics.clear(0.09, 0.1, 0.15)

    local rad_yaw = math.rad(cam.yaw)
    local rad_pitch = math.rad(cam.pitch)
    local target_x = cam.x + math.cos(rad_pitch) * math.sin(rad_yaw)
    local target_y = cam.y + math.sin(rad_pitch)
    local target_z = cam.z - math.cos(rad_pitch) * math.cos(rad_yaw)

    crayon.graphics.setCamera3d({
        position = {cam.x, cam.y, cam.z},
        target = {target_x, target_y, target_z},
        up = {0, 1, 0},
        fov = cam.fov
    })

    -- Ground grid
    for i = -15, 15, 3 do
        crayon.graphics.drawLine3d(i, 0.0, -15, i, 0.0, 15, 0.25, 0.3, 0.35, 1.0)
        crayon.graphics.drawLine3d(-15, 0.0, i, 15, 0.0, i, 0.25, 0.3, 0.35, 1.0)
    end

    -- Dynamic rigid obstacles
    for _, rb in ipairs(rigid_obstacles) do
        if rb and rb:isValid() then
            local x, y, z = rb:getPosition()
            crayon.graphics.setColor(0.8, 0.6, 0.2, 1.0)
            crayon.graphics.drawCube(x, y, z, 1.0, 1.0, 1.0)
        end
    end

    -- Steps (static)
    for i = 1, 6 do
        local step_y = (i - 1) * 0.8
        local step_z = -8.0 + (i - 1) * 2.0
        crayon.graphics.setColor(0.35, 0.4, 0.45, 1.0)
        crayon.graphics.drawCube(0, step_y + 0.4, step_z, 12.0, 0.8, 2.0)
    end

    -- Batched physics debug (wireframe soft body mesh + constraint rods)
    if show_debug then
        crayon.physics3d.drawDebug({
            shapes = true,
            softBodies = true,
            softBodyConstraints = true,
            constraints = true,
            bounds = false,
            velocities = false,
        })
    end

    -- 2D Overlay UI
    crayon.graphics.setColor(1.0, 1.0, 1.0, 1.0)
    crayon.graphics.drawText("== 3D Pressurized Ball & Volumetric Jelly Cubes ==", 20, 20, 1.0)
    crayon.graphics.drawText("WASD + Space/LShift : Fly camera | Arrow keys : Look", 20, 40, 1.0)
    crayon.graphics.drawText("[E] / [Q]           : Inflate / Deflate Ball Pressure", 20, 60, 1.0)
    crayon.graphics.drawText("Current Ball Pressure: " .. string.format("%.0f", pressure_val) .. " Pa", 20, 80, 1.0)
    if soft_ball and soft_ball:isValid() then
        local ok, vol = pcall(function() return soft_ball:getVolume() end)
        if ok then
            crayon.graphics.drawText("Current Ball Volume  : " .. string.format("%.3f", vol) .. " m^3", 20, 100, 1.0)
        end
    end
    crayon.graphics.drawText("[K]                 : Kick ball upward", 20, 120, 1.0)
    crayon.graphics.drawText("[TAB]               : Toggle Debug Lines (" .. (show_debug and "ON" or "OFF") .. ")", 20, 140, 1.0)
    crayon.graphics.drawText("[R]                 : Reset Simulation", 20, 160, 1.0)
    crayon.graphics.drawText("Features: Ideal Gas Pressure, Tetrahedron Volume Constraints, 2-Way Rigid Collision", 20, 190, 1.0)
end