-- ============================================================================
-- CRAYON TRUCK SIM  (articulated semi-truck)
--
--   W / UP       throttle                S / DOWN    brake / reverse
--   A / LEFT     steer left              D / RIGHT   steer right
--   SPACE        trailer handbrake       L           attach / detach trailer
--   MOUSE        orbit camera            WHEEL       zoom in/out
--   LSHIFT       turbo                   R           reset upright
--   C            camera mode             T           auto / manual transmission
--   Q / E        gear down / up (manual)
--   F1           wheel telemetry         F2          physics debug draw
--   H            help                    ESC         quit
--
-- Models generated by tools/gen_truck_models.py:
--   assets/tractor.glb, trailer.glb, truck_wheel.glb, cargo_crate.glb
-- ============================================================================

function crayon.config(t)
    t.modules.physics2D = false
    t.modules.physics4D = false
    t.modules.audio     = false
    t.modules.particles = false
    t.modules.fs        = false
end

local P = crayon.physics3D
local G = crayon.graphics
local K = crayon.key
local M = crayon.mouse

local sin, cos, sqrt, atan2, acos, abs, min, max, pi, exp =
    math.sin, math.cos, math.sqrt, math.atan2 or math.atan, math.acos, math.abs,
    math.min, math.max, math.pi, math.exp
local format = string.format

-- ---------------------------------------------------------------- helpers ---
local function clamp(v, lo, hi) return v < lo and lo or (v > hi and hi or v) end
local function lerp(a, b, t) return a + (b - a) * t end
local function angle_lerp(a, b, t)
    local d = (b - a + pi) % (2 * pi) - pi
    return a + d * t
end

local function axis_angle(x, y, z, w)
    if w < 0 then x, y, z, w = -x, -y, -z, -w end
    local s = sqrt(max(0, 1 - w * w))
    if s < 1e-4 then return 0, 1, 0, 0 end
    return x / s, y / s, z / s, 2 * acos(clamp(w, -1, 1))
end

local function quat_forward(x, y, z, w)
    return 2 * (x * z + w * y), 2 * (y * z - w * x), 1 - 2 * (x * x + y * y)
end

-- Rotate a local vector by a quaternion (used to project the tractor's
-- local fifth-wheel point into world space).
local function rotate_vec3(vx, vy, vz, qx, qy, qz, qw)
    -- v' = q * v * q^-1, expanded
    local ix =  qw * vx + qy * vz - qz * vy
    local iy =  qw * vy + qz * vx - qx * vz
    local iz =  qw * vz + qx * vy - qy * vx
    local iw = -qx * vx - qy * vy - qz * vz
    return ix * qw + iw * -qx + iy * -qz - iz * -qy,
           iy * qw + iw * -qy + iz * -qx - ix * -qz,
           iz * qw + iw * -qz + ix * -qy - iy * -qx
end

local function draw_with_pose(px, py, pz, qx, qy, qz, qw, fn)
    local ax, ay, az, ang = axis_angle(qx, qy, qz, qw)
    G.pushMatrix()
    G.translate(px, py, pz)
    if ang ~= 0 then G.rotate(ang, ax, ay, az) end
    fn()
    G.popMatrix()
end

-- ------------------------------------------------------------------ state ---
local models   = {}
local textures = {}
local tractor, trailer             = nil, nil        -- wheeled-vehicle handles
local tractor_body, trailer_body   = nil, nil        -- rigid bodies
local hitch                        = nil             -- constraint or nil
local err_msg = nil

local layout = "RWD"
local manual = false
local show_help, show_telemetry, show_debug = true, false, false
local cam_mode = 1
local steer_input = 0.0
local turbo = 100.0

local crates  = {}
local skids   = {}
local skid_last = {}

-- TRACTOR / TRAILER tuning --------------------------------------------------
-- All physics numbers are in the same units as the model generator's local
-- frame.  Spawn positions line up so the trailer's kingpin sits exactly on
-- the tractor's fifth wheel.
local TRACTOR = {
    half = { 1.20, 0.50, 2.80 },
    density = 320,                       -- ~2200 kg cab
    spawn = { x = 0, y = 1.10, z = 0 },
    fifth_wheel_local = { 0, 0.55, -2.50 },  -- relative to chassis centre
    wheel_radius = 0.55, wheel_width = 0.40,
    front_z =  1.80, rear_z = -1.80, x = 1.05, y = -0.55,
    spring_f = 90000, spring_r = 140000,
    damp_f   = 8000,  damp_r   = 11000,
    steer    = 0.40,
    brake_f  = 12000, brake_r  = 9000, hbrake_r = 14000,
}

local TRAILER = {
    half = { 1.25, 1.80, 5.00 },
    density = 110,                       -- ~2200 kg empty trailer
    spawn = { x = 0, y = 2.40, z = -7.50 },
    kingpin_local = { 0, -0.80, 5.00 },  -- relative to chassis centre
    wheel_radius = 0.55, wheel_width = 0.40,
    x = 1.05, rear_z = { -3.50, -4.50 }, landing_z = 3.50,
    rear_y = -1.85, landing_y = -1.55,
    spring_r = 110000, damp_r = 9000,
    spring_l = 180000, damp_l = 16000,   -- stiff landing gear
}

local cached_dt = 1 / 60
local cached_w  = 320
local cached_h  = 240

-- CAMERA --------------------------------------------------------------------
local cam = { heading = 0 }
local orbit = {
    yaw = 0.0, pitch = 0.30, dist = 14.0,
    sens = 0.0030, pitch_min = -0.10, pitch_max = 1.00,
    default_pitch = 0.30, idle = 0.0,
    recenter_delay_yaw = 0.40, recenter_delay_pitch = 1.20,
    recenter_base_rate = 0.6, recenter_max_rate = 2.5,
}
local cam_tbl = { position = {0,0,0}, target = {0,0,0}, up = {0,1,0}, fov = 62 }

-- --------------------------------------------------------------- world ------
local function build_world()
    P.createPlane(0, 0, 0, 0, 1, 0, 800)

    -- Scattered cargo crates near the start so you have something to hit.
    for _, s in ipairs({
        { -6, 0.5,  18 }, { -3, 0.5,  18 }, { 0, 0.5, 18 }, { 3, 0.5, 18 }, { 6, 0.5, 18 },
        { -6, 0.5,  26 }, { -3, 0.5,  26 }, { 0, 0.5, 26 }, { 3, 0.5, 26 }, { 6, 0.5, 26 },
    }) do
        crates[#crates + 1] = P.createBox(s[1], s[2], s[3], 0.5, 0.5, 0.5, "dynamic", 0.7, 0.15, 300)
    end
end

-- ------------------------------------------------------------- vehicles -----
local function tractor_wheels()
    local fd = (layout == "FWD" or layout == "AWD")
    local rd = (layout == "RWD" or layout == "AWD")
    local function w(sx, z, front, drive, spring, damp, brake, hbrake)
        return {
            pos                   = { sx * TRACTOR.x, TRACTOR.y, z },
            radius                = TRACTOR.wheel_radius,
            width                 = TRACTOR.wheel_width,
            suspensionMinLength   = 0.10,
            suspensionMaxLength   = 0.40,
            suspensionSpring      = spring,
            suspensionDamping     = damp,
            maxSteerAngleRad      = front and TRACTOR.steer or 0.0,
            maxBrakeTorque        = brake,
            maxHandBrakeTorque    = hbrake,
            isFront               = front,
            isDrive               = drive,
        }
    end
    return {
        w( 1, TRACTOR.front_z, true,  fd, TRACTOR.spring_f, TRACTOR.damp_f, TRACTOR.brake_f, 0),
        w(-1, TRACTOR.front_z, true,  fd, TRACTOR.spring_f, TRACTOR.damp_f, TRACTOR.brake_f, 0),
        w( 1, TRACTOR.rear_z,  false, rd, TRACTOR.spring_r, TRACTOR.damp_r, TRACTOR.brake_r, TRACTOR.hbrake_r),
        w(-1, TRACTOR.rear_z,  false, rd, TRACTOR.spring_r, TRACTOR.damp_r, TRACTOR.brake_r, TRACTOR.hbrake_r),
    }
end

local function trailer_wheels()
    local list = {}
    -- Rear tandem: 4 wheels
    for _, z in ipairs(TRAILER.rear_z) do
        for _, sx in ipairs({ 1, -1 }) do
            list[#list + 1] = {
                pos = { sx * TRAILER.x, TRAILER.rear_y, z },
                radius = TRAILER.wheel_radius, width = TRAILER.wheel_width,
                suspensionMinLength = 0.10, suspensionMaxLength = 0.35,
                suspensionSpring = TRAILER.spring_r, suspensionDamping = TRAILER.damp_r,
                maxSteerAngleRad = 0, maxBrakeTorque = 2500, maxHandBrakeTorque = 8000,
                isFront = false, isDrive = false,
            }
        end
    end
    -- Landing gear legs (wheels, so they roll when they touch)
    for _, sx in ipairs({ 1, -1 }) do
        list[#list + 1] = {
            pos = { sx * 0.90, TRAILER.landing_y, TRAILER.landing_z },
            radius = TRAILER.wheel_radius, width = TRAILER.wheel_width,
            suspensionMinLength = 0.02, suspensionMaxLength = 0.10,
            suspensionSpring = TRAILER.spring_l, suspensionDamping = TRAILER.damp_l,
            maxSteerAngleRad = 0, maxBrakeTorque = 0, maxHandBrakeTorque = 0,
            isFront = false, isDrive = false,
        }
    end
    return list
end

local function spawn_tractor()
    local s = TRACTOR.spawn
    tractor_body = P.createBox(s.x, s.y, s.z,
        TRACTOR.half[1], TRACTOR.half[2], TRACTOR.half[3],
        "dynamic", 0.6, 0.1, TRACTOR.density)
    tractor_body:setDamping(0.02, 0.55)
    tractor_body:setMotionQuality(true)

    local ok, v = pcall(P.createWheeledVehicle, {
        chassis = tractor_body,
        wheels  = tractor_wheels(),
        maxPitchRollAngle = math.rad(70),

        engineMaxTorque = 2400, engineMinRpm = 500, engineMaxRpm = 2100,
        engineInertia   = 3.0,
        torqueCurve = { {0.0, 0.90}, {0.20, 1.00}, {0.55, 0.95}, {0.80, 0.75}, {1.0, 0.50} },

        transmission = manual and "manual" or "auto",
        gearRatios   = { 7.0, 4.0, 2.4, 1.6, 1.15, 0.90 },
        reverseGearRatios = { 6.0 },
        shiftUpRpm = 1800, shiftDownRpm = 800, clutchStrength = 45,

        differentialRatio      = 4.5,
        limitedSlipRatio       = 2.0,
        centerLimitedSlipRatio = 2.0,
        frontTorqueSplit       = 0.25,

        antiRollFront = 20000,
        antiRollRear  = 30000,
        collisionTester = "ray",
    })
    if not ok then err_msg = tostring(v); return nil end
    if manual then v:setGear(1, 1.0) end
    return v
end

local function spawn_trailer()
    local s = TRAILER.spawn
    trailer_body = P.createBox(s.x, s.y, s.z,
        TRAILER.half[1], TRAILER.half[2], TRAILER.half[3],
        "dynamic", 0.7, 0.05, TRAILER.density)
    trailer_body:setDamping(0.02, 0.40)
    trailer_body:setMotionQuality(true)

    local ok, v = pcall(P.createWheeledVehicle, {
        chassis = trailer_body,
        wheels  = trailer_wheels(),
        maxPitchRollAngle = math.rad(80),
        engineMaxTorque = 0, engineMinRpm = 0, engineMaxRpm = 1,
        transmission = "manual",
        antiRollFront = 0,
        antiRollRear  = 8000,
        collisionTester = "ray",
    })
    if not ok then err_msg = tostring(v); return nil end
    return v
end

-- --------------------------------------------------------------- hitch ------
local function fifth_wheel_world()
    if not (tractor_body and tractor_body:isValid()) then return nil end
    local tx, ty, tz = tractor_body:getPosition()
    local qx, qy, qz, qw = tractor_body:getQuaternion()
    local fw = TRACTOR.fifth_wheel_local
    local dx, dy, dz = rotate_vec3(fw[1], fw[2], fw[3], qx, qy, qz, qw)
    return tx + dx, ty + dy, tz + dz
end

local function kingpin_world()
    if not (trailer_body and trailer_body:isValid()) then return nil end
    local tx, ty, tz = trailer_body:getPosition()
    local qx, qy, qz, qw = trailer_body:getQuaternion()
    local kp = TRAILER.kingpin_local
    local dx, dy, dz = rotate_vec3(kp[1], kp[2], kp[3], qx, qy, qz, qw)
    return tx + dx, ty + dy, tz + dz
end

local function attach_trailer()
    if hitch then hitch:destroy(); hitch = nil end
    if not (tractor_body and tractor_body:isValid()) then return false end
    if not (trailer_body and trailer_body:isValid()) then return false end

    local tx, ty, tz = tractor_body:getPosition()
    local tqx, tqy, tqz, tqw = tractor_body:getQuaternion()

    -- Target world position of the tractor's fifth wheel.
    local fx, fy, fz = fifth_wheel_world()

    -- Where is the trailer's kingpin right now?
    local kx, ky, kz = kingpin_world()
    local dx, dy, dz = fx - kx, fy - ky, fz - kz
    local dist = sqrt(dx*dx + dy*dy + dz*dz)

    -- If we're not reasonably close, refuse (like a real truck sim).
    if dist > 4.0 then
        return false
    end

    -- Snap the trailer so the kingpin sits exactly at the fifth wheel,
    -- keeping the trailer's current orientation.
    local px, py, pz = trailer_body:getPosition()
    trailer_body:setPosition(px + dx, py + dy, pz + dz, true)

    -- Create the hinge at the fifth wheel: world vertical axis.
    hitch = P.createHingeConstraint(tractor_body, trailer_body, fx, fy, fz, 0, 1, 0)
    return true
end

local function detach_trailer()
    if hitch then
        hitch:destroy()
        hitch = nil
    end
end

-- --------------------------------------------------------------- lifecycle --
local function reset_all()
    if hitch then hitch:destroy(); hitch = nil end
    P.destroyAll()
    crates = {}
    skids  = {}
    skid_last = {}

    P.setGravity(0, -9.81, 0)
    build_world()
    tractor = spawn_tractor()
    trailer = spawn_trailer()
    attach_trailer()

    cam.heading = 0
    orbit.yaw = 0
    orbit.pitch = orbit.default_pitch
    orbit.idle = 0
end

function crayon.init()
    P = crayon.physics3D
    G = crayon.graphics
    K = crayon.key
    M = crayon.mouse

    crayon.window.setTitle("Crayon Truck Sim")
    crayon.window.setResolution(320, 240)
    cached_w, cached_h = crayon.window.getResolution()

    crayon.window.setMouseRelative(true)
    crayon.window.showCursor(false)

    models.tractor = G.loadModel("assets/tractor.glb")
    models.trailer = G.loadModel("assets/trailer.glb")
    models.wheel   = G.loadModel("assets/truck_wheel.glb")
    models.crate   = G.loadModel("assets/cargo_crate.glb")

    textures.ground = G.loadTexture("assets/grass.bmp")

    reset_all()

    G.setLight(-0.45, -1.0, -0.35, 1.0, 0.95, 0.85, 0.38, 0.38, 0.45)
    G.setRetroEffects({ fog = { startDist = 80, endDist = 180, color = { 0.55, 0.72, 0.92 } } })
end

function crayon.windowResized(w, h)
    cached_w, cached_h = w, h
end

-- --------------------------------------------------------------- driving ----
local function update_driver(dt)
    if not (tractor and tractor:isValid()) then return end

    local up    = K.isDown("w") or K.isDown("up")
    local down  = K.isDown("s") or K.isDown("down")
    local left  = K.isDown("a") or K.isDown("left")
    local right = K.isDown("d") or K.isDown("right")
    local hbrake = K.isDown("space") and 1.0 or 0.0

    local fwd_speed = tractor:getForwardSpeed()
    local speed_kmh = tractor:getSpeedKmh()

    local throttle, brake = 0.0, 0.0
    if manual then
        throttle = up   and 1.0 or 0.0
        brake    = down and 1.0 or 0.0
    else
        if up then
            if fwd_speed < -1.0 then brake = 1.0 else throttle = 1.0 end
        end
        if down then
            if fwd_speed > 1.0 then brake = 1.0; throttle = 0.0
            else throttle = -1.0 end
        end
    end

    -- Steering: trucks steer slowly.  Rate narrows with speed.
    local target = (right and 1 or 0) - (left and 1 or 0)
    local speed_factor = 1.0 / (1.0 + (speed_kmh / 40.0) ^ 2)
    local rate = (target == 0) and 4.0 or 2.5
    steer_input = steer_input + (target * speed_factor - steer_input) * min(1.0, rate * dt)

    tractor:setInputWheeled(throttle, steer_input, brake, hbrake)

    if manual then
        local gear = tractor:getTransmissionGear()
        if K.isPressed("e") then tractor:setGear(min(gear + 1, 6), 1.0) end
        if K.isPressed("q") then tractor:setGear(max(gear - 1, -1), 1.0) end
    end

    -- Rolling resistance on the tractor.
    local vx, vy, vz = tractor_body:getVelocity()
    local speed = sqrt(vx*vx + vy*vy + vz*vz)
    local drag = 0.35 * speed * dt
    tractor_body:applyImpulse(-vx * drag, -vy * drag * 0.2, -vz * drag)

    -- Turbo
    if K.isDown("lshift") and turbo > 0 and throttle > 0 then
        local qx, qy, qz, qw = tractor_body:getQuaternion()
        local fx, fy, fz = quat_forward(qx, qy, qz, qw)
        local f = 40000 * dt
        tractor_body:applyImpulse(fx * f, fy * f, fz * f)
        turbo = max(0, turbo - 20 * dt)
    else
        turbo = min(100, turbo + 4 * dt)
    end
end

-- ------------------------------------------------------------- mouse look ---
local function update_mouse_look(dt)
    local dx, dy = M.getDelta()

    local _, wdy = M.getWheel()
    if wdy and abs(wdy) > 0.001 then
        orbit.dist = clamp(orbit.dist - wdy * 0.7, 8.0, 32.0)
    end

    if dx and dy and (abs(dx) > 0.001 or abs(dy) > 0.001) then
        orbit.yaw   = orbit.yaw - dx * orbit.sens
        orbit.pitch = clamp(orbit.pitch - dy * orbit.sens, orbit.pitch_min, orbit.pitch_max)
        orbit.idle  = 0
    else
        orbit.idle = orbit.idle + dt
    end

    if orbit.idle > orbit.recenter_delay_yaw then
        local kmh = tractor and tractor:getSpeedKmh() or 0
        if kmh > 4 then
            if orbit.yaw >  pi then orbit.yaw = orbit.yaw - 2*pi end
            if orbit.yaw < -pi then orbit.yaw = orbit.yaw + 2*pi end
            local rate = orbit.recenter_base_rate
                + (orbit.recenter_max_rate - orbit.recenter_base_rate) * min(kmh / 40.0, 1.0)
            orbit.yaw = orbit.yaw * exp(-rate * dt)
        end
    end
    if orbit.idle > orbit.recenter_delay_pitch then
        orbit.pitch = orbit.pitch + (orbit.default_pitch - orbit.pitch) * min(1.0, dt * 1.4)
    end
end

-- ------------------------------------------------------------- skid marks ---
local skid_parity = 0
local function update_skids()
    if not (tractor and tractor:isValid()) then return end
    skid_parity = 1 - skid_parity
    if skid_parity ~= 0 then return end

    for i = 1, 4 do
        local info = tractor:getWheelInfo(i - 1)
        if info and info.contact and info.skid > 0.55 then
            local p = info.contactPos
            local last = skid_last[i]
            local cur = { p.x, p.y + 0.02, p.z }
            if last then
                local ddx, ddz = cur[1] - last[1], cur[3] - last[3]
                local d = sqrt(ddx*ddx + ddz*ddz)
                if d > 0.35 and d < 5.0 then
                    local lx, lz = -ddz / d * 0.16, ddx / d * 0.16
                    skids[#skids + 1] = {
                        {last[1] + lx, last[2], last[3] + lz},
                        {last[1] - lx, last[2], last[3] - lz},
                        {cur[1] - lx, cur[2], cur[3] - lz},
                        {cur[1] + lx, cur[2], cur[3] + lz},
                    }
                    if #skids > 80 then table.remove(skids, 1) end
                    skid_last[i] = cur
                elseif d >= 5.0 then
                    skid_last[i] = cur
                end
            else
                skid_last[i] = cur
            end
        else
            skid_last[i] = nil
        end
    end
end

-- ------------------------------------------------------------- main update --
function crayon.update(dt)
    dt = min(dt, 0.05)
    cached_dt = dt

    if K.isPressed("escape") then crayon.window.quit() end

    -- Hitch toggle
    if K.isPressed("l") then
        if hitch then
            detach_trailer()
        else
            attach_trailer()
        end
    end

    if K.isPressed("1") then layout = "RWD"; if tractor then tractor:destroy() end; tractor = spawn_tractor(); if hitch then attach_trailer() end end
    if K.isPressed("2") then layout = "FWD"; if tractor then tractor:destroy() end; tractor = spawn_tractor(); if hitch then attach_trailer() end end
    if K.isPressed("3") then layout = "AWD"; if tractor then tractor:destroy() end; tractor = spawn_tractor(); if hitch then attach_trailer() end end

    if K.isPressed("t") then
        manual = not manual
        if tractor then
            tractor:setManualTransmission(manual)
            if manual then tractor:setGear(1, 1.0) end
        end
    end
    if K.isPressed("c") then
        cam_mode = cam_mode % 4 + 1
        if     cam_mode == 1 then orbit.dist = 14.0
        elseif cam_mode == 2 then orbit.dist = 24.0
        elseif cam_mode == 4 then orbit.dist = 28.0 end
    end
    if K.isPressed("h")  then show_help = not show_help end
    if K.isPressed("f1") then show_telemetry = not show_telemetry end
    if K.isPressed("f2") then show_debug = not show_debug end
    if K.isPressed("r")  then reset_all() end

    update_driver(dt)
    update_mouse_look(dt)
    update_skids()
end

-- ------------------------------------------------------------------ camera --
local function update_camera()
    if not (tractor_body and tractor_body:isValid()) then return end

    -- Camera aims at a point roughly 1/3 back along the tractor+trailer rig.
    local px, py, pz = tractor_body:getPosition()
    local qx, qy, qz, qw = tractor_body:getQuaternion()
    local fx, fy, fz = quat_forward(qx, qy, qz, qw)
    local car_heading = atan2(fx, fz)

    cam.heading = angle_lerp(cam.heading, car_heading, min(1, cached_dt * 4.0))

    local speed = tractor and tractor:getSpeedKmh() or 0
    local fov_target = 62 + clamp(speed * 0.10, 0, 15)
    cam_tbl.fov = lerp(cam_tbl.fov, fov_target, min(1, cached_dt * 3))

    local pos, target = cam_tbl.position, cam_tbl.target
    local h = cam.heading + orbit.yaw
    local hx, hz = sin(h), cos(h)
    local cos_p, sin_p = cos(orbit.pitch), sin(orbit.pitch)

    local horiz = orbit.dist * cos_p
    local vert  = orbit.dist * sin_p

    pos[1] = px - hx * horiz
    pos[2] = max(py + 2.6 + vert, 1.2)
    pos[3] = pz - hz * horiz

    target[1] = px + hx * 4.0
    target[2] = py + 1.2
    target[3] = pz + hz * 4.0

    G.setCamera3D(cam_tbl)
end

-- -------------------------------------------------------------------- draw -
local function draw_world()
    G.setColor(1, 1, 1, 1)
    G.drawPlane(0, 0, 0, 500, 500, textures.ground)

    for _, b in ipairs(crates) do
        if b:isValid() then
            local x, y, z = b:getPosition()
            local qx, qy, qz, qw = b:getQuaternion()
            G.setColor(1, 1, 1, 1)
            draw_with_pose(x, y, z, qx, qy, qz, qw, function()
                G.drawModel(models.crate, 0, 0, 0, 0, 0, 0, 1, 1, 1)
            end)
        end
    end

    G.setColor(0.04, 0.04, 0.05, 1)
    for _, q in ipairs(skids) do
        G.drawQuad3D(q[1], q[2], q[3], q[4])
        G.drawQuad3D(q[4], q[3], q[2], q[1])
    end
end

local function draw_vehicle_pair()
    if tractor_body and tractor_body:isValid() then
        local x, y, z = tractor_body:getPosition()
        local qx, qy, qz, qw = tractor_body:getQuaternion()
        G.setColor(1, 1, 1, 1)
        draw_with_pose(x, y, z, qx, qy, qz, qw, function()
            G.drawModel(models.tractor, 0, 0, 0, 0, 0, 0, 1, 1, 1)
        end)

        if tractor and tractor:isValid() then
            for i = 0, tractor:getWheelCount() - 1 do
                local t = tractor:getWheelTransform(i)
                if t then
                    local r = t.rotation
                    draw_with_pose(t.position.x, t.position.y, t.position.z,
                                   r.x, r.y, r.z, r.w,
                        function() G.drawModel(models.wheel, 0, 0, 0, 0, 0, 0, 1, 1, 1) end)
                end
            end
        end
    end

    if trailer_body and trailer_body:isValid() then
        local x, y, z = trailer_body:getPosition()
        local qx, qy, qz, qw = trailer_body:getQuaternion()
        G.setColor(1, 1, 1, 1)
        draw_with_pose(x, y, z, qx, qy, qz, qw, function()
            G.drawModel(models.trailer, 0, 0, 0, 0, 0, 0, 1, 1, 1)
        end)

        if trailer and trailer:isValid() then
            for i = 0, trailer:getWheelCount() - 1 do
                local t = trailer:getWheelTransform(i)
                if t then
                    local r = t.rotation
                    draw_with_pose(t.position.x, t.position.y, t.position.z,
                                   r.x, r.y, r.z, r.w,
                        function() G.drawModel(models.wheel, 0, 0, 0, 0, 0, 0, 1, 1, 1) end)
                end
            end
        end
    end
end

local function bar(x, y, w, h, frac, r, g, b)
    G.setColor(0, 0, 0, 0.55); G.drawRect("fill", x - 2, y - 2, w + 4, h + 4)
    G.setColor(r, g, b, 1);    G.drawRect("fill", x, y, w * clamp(frac, 0, 1), h)
end

local function draw_hud()
    local W, H = cached_w, cached_h

    if not (tractor and tractor:isValid()) then
        G.setColor(1, 0.3, 0.3, 1)
        G.drawText("Truck failed to build: " .. tostring(err_msg), 20, 20)
        return
    end

    local speed = tractor:getSpeedKmh()
    local rpm   = tractor:getEngineRpm()
    local gear  = tractor:getTransmissionGear()
    local gtxt  = gear < 0 and "R" or (gear == 0 and "N" or tostring(gear))

    G.setColor(1, 1, 1, 1)
    G.drawText(format("%3d", speed), 24, H - 90, { scale = 2.4 })
    G.drawText("km/h", 116, H - 56, { scale = 1.1 })
    G.drawText(gtxt, 160, H - 96, { scale = 2.4 })

    bar(24, H - 24, 200, 8, rpm / 2100,
        rpm > 1800 and 1 or 0.2, rpm > 1800 and 0.2 or 0.85, 0.2)
    bar(24, H - 38, 100, 5, turbo / 100, 0.2, 0.6, 1.0)

    G.setColor(0.9, 0.9, 1, 1)
    G.drawText(format("%s | %s", layout, manual and "MAN" or "AUTO"), 24, 20)

    -- Hitch indicator (bright when attached)
    if hitch then
        G.setColor(0.3, 1.0, 0.4, 1)
        G.drawText("HITCH: ATTACHED", 24, 36)
    else
        G.setColor(1.0, 0.5, 0.2, 1)
        G.drawText("HITCH: DETACHED  (press L near trailer)", 24, 36)
    end

    if show_telemetry then
        G.setColor(0, 0, 0, 0.55); G.drawRect("fill", W - 330, 70, 316, 100)
        G.setColor(1, 1, 1, 1)
        local names = { "FL", "FR", "RL", "RR" }
        for i = 1, 4 do
            local w = tractor:getWheelInfo(i - 1)
            if w then
                G.drawText(format("%s %s susp %.2f  slip %+.2f/%+.2f",
                    names[i], w.contact and "GND" or "AIR",
                    w.suspension, w.longSlip, w.latSlip), W - 322, 78 + (i - 1) * 16)
            end
        end
        G.drawText(format("fwd %.1f m/s", tractor:getForwardSpeed()), W - 322, 148)
    end

    if show_help then
        G.setColor(0, 0, 0, 0.55); G.drawRect("fill", 14, 56, 300, 144)
        G.setColor(0.95, 0.95, 0.95, 1)
        local lines = {
            "W/S throttle+brake  A/D steer",
            "SPACE trailer brake  L hitch on/off",
            "MOUSE look  WHEEL zoom  LSHIFT turbo",
            "C camera  T auto/manual (Q/E shift)",
            "1/2/3 RWD/FWD/AWD",
            "R reset  F1 telemetry  F2 debug  H hide",
        }
        for i, l in ipairs(lines) do G.drawText(l, 22, 64 + (i - 1) * 16) end
    end
end

function crayon.draw()
    G.clear(0.55, 0.72, 0.92, 1)
    update_camera()
    if not show_debug then
        draw_world()
        draw_vehicle_pair()
    end
    if show_debug then P.drawDebug({ vehicles = true, shapes = true, constraints = true }) end
    draw_hud()
end