#pragma once

#include <string>

namespace crayon::android {

// On Android a game's files live inside the APK (read-only, no real paths), but the
// engine - Lua require(), stb_image, tinyobj, tinygltf, fonts, hot reload - works on
// real filesystem paths. So at startup we make the game available on disk:
//
//   1. DEV OVERRIDE:  <external files dir>/game/   (adb push friendly, no rebuild needed)
//        /sdcard/Android/data/<package>/files/game/
//      Used if it contains `.crayonproj` or `main.lua`.
//   2. PACKAGED GAME: APK assets/game/**  ->  <internal storage>/game/
//      Copied on first launch and again whenever the APK's asset list changes.
//
// Returns the directory to use as the project root, or "" if no game was found.
//
// The APK must contain `assets/crayon_assets.txt` (generated by the Gradle task in
// android/app/build.gradle): one relative path per line, first line "# stamp:<id>".
std::string prepare_game_root();

} // namespace crayon::android
